# Generated by Django 5.1 on 2024-08-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user',
            field=models.CharField(),
        ),
    ]
